export type ContactFormLocale = "en" | "es" | "fr";

export const contactFormCopy = {
  en: {
    contactTitle: "Contact Famdesc",
    contactSubtitle:
      "Reach the Famdesc team for support, partnerships, FSA product questions, suppliers, press, or commercial conversations.",
    formTitle: "Send a message",
    formSubtitle: "Tell us what you need and we will route it to the right person.",
    name: "Name",
    email: "Email",
    subject: "Subject",
    message: "Message",
    inquiryType: "Inquiry type",
    general: "General",
    fsa: "FSA Line One Pro",
    partnership: "Partnership",
    support: "Support",
    send: "Send message",
    sending: "Sending...",
    success:
      "Thank you. Your message has been sent successfully. We will get back to you as soon as possible.",
    error: "We could not send your request right now. Please try again in a few minutes.",
    responseTime: "We usually reply within 1-2 business days.",
    knowledgebase: "Knowledgebase",
    knowledgebaseText: "Browse through all of our knowledgebase articles.",
    knowledgebaseLink: "Visit guides & tutorials",
    faq: "FAQ",
    faqText: "Explore our FAQ for quick, clear answers to common queries.",
    faqLink: "Visit FAQ",
    office: "Visit our office",
    company: "Famdesc LLC",
    emailBlock: "Contact us by email",
    emailText: "Prefer the written word? Drop us an email at",
    waitlistLink: "Looking for early access?",
    waitlistLinkText: "Join the waitlist instead",
  },
  es: {
    contactTitle: "Contacta a Famdesc",
    contactSubtitle:
      "Escríbenos para soporte, colaboraciones, preguntas sobre FSA, proveedores, prensa o consultas comerciales.",
    formTitle: "Enviar un mensaje",
    formSubtitle: "Cuéntanos qué necesitas y lo dirigiremos a la persona adecuada.",
    name: "Nombre",
    email: "Email",
    subject: "Asunto",
    message: "Mensaje",
    inquiryType: "Tipo de consulta",
    general: "General",
    fsa: "FSA Line One Pro",
    partnership: "Colaboración",
    support: "Soporte",
    send: "Enviar mensaje",
    sending: "Enviando...",
    success:
      "Gracias. Tu mensaje se envió correctamente. Te responderemos lo antes posible.",
    error: "No pudimos enviar tu solicitud ahora. Inténtalo nuevamente en unos minutos.",
    responseTime: "Normalmente respondemos en 1-2 días hábiles.",
    knowledgebase: "Base de conocimientos",
    knowledgebaseText: "Explora todos nuestros artículos de la base de conocimientos.",
    knowledgebaseLink: "Visitar guías y tutoriales",
    faq: "Preguntas frecuentes",
    faqText: "Encuentra respuestas rápidas y claras a consultas comunes.",
    faqLink: "Visitar FAQ",
    office: "Visita nuestra oficina",
    company: "Famdesc LLC",
    emailBlock: "Contáctanos por correo electrónico",
    emailText: "¿Prefieres escribirnos? Envíanos un correo a",
    waitlistLink: "¿Buscas acceso temprano?",
    waitlistLinkText: "Únete a la lista de espera",
  },
  fr: {
    contactTitle: "Contactez Famdesc",
    contactSubtitle:
      "Contactez-nous pour le support, les partenariats, les questions sur FSA, les fournisseurs, la presse ou les échanges commerciaux.",
    formTitle: "Envoyer un message",
    formSubtitle: "Dites-nous ce dont vous avez besoin et nous l'adresserons à la bonne personne.",
    name: "Nom",
    email: "E-mail",
    subject: "Sujet",
    message: "Message",
    inquiryType: "Type de demande",
    general: "Général",
    fsa: "FSA Line One Pro",
    partnership: "Partenariat",
    support: "Support",
    send: "Envoyer le message",
    sending: "Envoi...",
    success:
      "Merci. Votre message a bien été envoyé. Nous vous répondrons dès que possible.",
    error: "Nous n'avons pas pu envoyer votre demande. Veuillez réessayer dans quelques minutes.",
    responseTime: "Nous répondons généralement sous 1 à 2 jours ouvrables.",
    knowledgebase: "Base de connaissances",
    knowledgebaseText: "Parcourez tous nos articles de base de connaissances.",
    knowledgebaseLink: "Visiter les guides et tutoriels",
    faq: "FAQ",
    faqText: "Consultez notre FAQ pour des réponses rapides et claires.",
    faqLink: "Visiter la FAQ",
    office: "Visitez notre bureau",
    company: "Famdesc LLC",
    emailBlock: "Contactez-nous par e-mail",
    emailText: "Vous préférez l'écrit ? Envoyez-nous un e-mail à",
    waitlistLink: "Vous cherchez un accès anticipé ?",
    waitlistLinkText: "Rejoindre la liste d'attente",
  },
} as const;

export const waitlistFormCopy = {
  en: {
    title: "Join the Famdesc waitlist",
    subtitle:
      "Get early updates about FSA Line One Pro and the future Famdesc social platform without mixing your request with support messages.",
    formTitle: "Reserve your place",
    formSubtitle: "Choose what you want to hear about first.",
    name: "Name",
    email: "Email",
    interest: "Interest",
    fsa: "FSA Line One Pro",
    social: "Famdesc Social Platform",
    both: "Both",
    join: "Join waitlist",
    joining: "Joining...",
    success:
      "Thank you for joining the Famdesc waitlist. We will keep you updated about FSA and the future social platform.",
    error: "We could not send your request right now. Please try again in a few minutes.",
    contactLink: "Need to send a message?",
    contactLinkText: "Go to contact",
    privacy: "No noise. Only product and launch updates when there is something useful to share.",
    fsaBlock: "FSA product updates",
    fsaBlockText: "Follow launch notes, availability, and product progress for FSA Line One Pro.",
    platformBlock: "Social platform updates",
    platformBlockText: "Get early notes as the Famdesc family social platform takes shape.",
    emailBlock: "Direct contact",
    emailBlockText: "For support or business messages, use the contact page or email",
  },
  es: {
    title: "Únete a la lista de espera de Famdesc",
    subtitle:
      "Recibe novedades tempranas sobre FSA Line One Pro y la futura plataforma social de Famdesc sin mezclar tu solicitud con mensajes de soporte.",
    formTitle: "Reserva tu lugar",
    formSubtitle: "Elige sobre qué quieres recibir noticias primero.",
    name: "Nombre",
    email: "Email",
    interest: "Interés",
    fsa: "FSA Line One Pro",
    social: "Famdesc Social Platform",
    both: "Ambos",
    join: "Unirme a la lista",
    joining: "Uniendo...",
    success:
      "Gracias por unirte a la lista de espera de Famdesc. Te mantendremos al tanto sobre FSA y la futura plataforma social.",
    error: "No pudimos enviar tu solicitud ahora. Inténtalo nuevamente en unos minutos.",
    contactLink: "¿Necesitas enviar un mensaje?",
    contactLinkText: "Ir a contacto",
    privacy: "Sin ruido. Solo novedades de producto y lanzamiento cuando haya algo útil que compartir.",
    fsaBlock: "Novedades de FSA",
    fsaBlockText: "Sigue notas de lanzamiento, disponibilidad y progreso de FSA Line One Pro.",
    platformBlock: "Novedades de la plataforma social",
    platformBlockText: "Recibe notas tempranas mientras toma forma la plataforma social familiar de Famdesc.",
    emailBlock: "Contacto directo",
    emailBlockText: "Para soporte o mensajes comerciales, usa la página de contacto o escribe a",
  },
  fr: {
    title: "Rejoindre la liste d'attente Famdesc",
    subtitle:
      "Recevez les premières nouvelles de FSA Line One Pro et de la future plateforme sociale Famdesc sans mélanger votre demande avec les messages de support.",
    formTitle: "Réserver votre place",
    formSubtitle: "Choisissez ce que vous voulez suivre en premier.",
    name: "Nom",
    email: "E-mail",
    interest: "Intérêt",
    fsa: "FSA Line One Pro",
    social: "Famdesc Social Platform",
    both: "Les deux",
    join: "Rejoindre la liste",
    joining: "Inscription...",
    success:
      "Merci d'avoir rejoint la liste d'attente Famdesc. Nous vous tiendrons informé de FSA et de la future plateforme sociale.",
    error: "Nous n'avons pas pu envoyer votre demande. Veuillez réessayer dans quelques minutes.",
    contactLink: "Besoin d'envoyer un message ?",
    contactLinkText: "Aller au contact",
    privacy: "Pas de bruit. Seulement des nouvelles utiles sur le produit et le lancement.",
    fsaBlock: "Nouvelles FSA",
    fsaBlockText: "Suivez les notes de lancement, la disponibilité et les progrès de FSA Line One Pro.",
    platformBlock: "Nouvelles de la plateforme sociale",
    platformBlockText: "Recevez les premières notes pendant que la plateforme sociale familiale Famdesc prend forme.",
    emailBlock: "Contact direct",
    emailBlockText: "Pour le support ou les messages commerciaux, utilisez la page de contact ou écrivez à",
  },
} as const;
